kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: core-auth-proxy-auth-delegator
subjects:
  - kind: ServiceAccount
    name: noobaa-core
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:auth-delegator'